-- +goose Up
CREATE TABLE linkding_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind text NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL CHECK (status IN ('pending', 'running', 'complete', 'failed')),
    attempts integer NOT NULL DEFAULT 0,
    lease_token text NOT NULL DEFAULT '',
    available_at timestamp with time zone NOT NULL,
    leased_until timestamp with time zone NULL,
    last_error text NOT NULL DEFAULT '',
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);
CREATE INDEX linkding_job_ready_idx ON linkding_job (status, available_at, id);
CREATE INDEX linkding_job_lease_idx ON linkding_job (status, leased_until);
