-- Schema generated by pg_dump from sissbruecker/linkding:1.47.0 after Django migrations.
-- +goose Up
CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: bookmarks_apitoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_apitoken (
    id integer NOT NULL,
    key character varying(40) NOT NULL,
    name character varying(128) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: bookmarks_apitoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_apitoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_apitoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_bookmark; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_bookmark (
    id integer NOT NULL,
    url character varying(2048) NOT NULL,
    title character varying(512) NOT NULL,
    description text NOT NULL,
    website_title character varying(512),
    website_description text,
    unread boolean NOT NULL,
    date_added timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    date_accessed timestamp with time zone,
    owner_id integer NOT NULL,
    is_archived boolean NOT NULL,
    web_archive_snapshot_url character varying(2048) NOT NULL,
    shared boolean NOT NULL,
    favicon_file character varying(512) NOT NULL,
    notes text NOT NULL,
    preview_image_file character varying(512) NOT NULL,
    latest_snapshot_id integer,
    url_normalized character varying(2048) NOT NULL
);


--
-- Name: bookmarks_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_bookmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_bookmark_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_bookmark_tags (
    id integer NOT NULL,
    bookmark_id integer NOT NULL,
    tag_id integer NOT NULL
);


--
-- Name: bookmarks_bookmark_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_bookmark_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_bookmark_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_bookmarkasset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_bookmarkasset (
    id integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    file character varying(2048) NOT NULL,
    file_size integer,
    asset_type character varying(64) NOT NULL,
    content_type character varying(128) NOT NULL,
    display_name character varying(2048) NOT NULL,
    status character varying(64) NOT NULL,
    gzip boolean NOT NULL,
    bookmark_id integer NOT NULL
);


--
-- Name: bookmarks_bookmarkasset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_bookmarkasset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_bookmarkasset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_bookmarkbundle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_bookmarkbundle (
    id integer NOT NULL,
    name character varying(256) NOT NULL,
    search character varying(256) NOT NULL,
    any_tags character varying(1024) NOT NULL,
    all_tags character varying(1024) NOT NULL,
    excluded_tags character varying(1024) NOT NULL,
    "order" integer NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_modified timestamp with time zone NOT NULL,
    owner_id integer NOT NULL,
    filter_shared character varying(3) NOT NULL,
    filter_unread character varying(3) NOT NULL
);


--
-- Name: bookmarks_bookmarkbundle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_bookmarkbundle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_bookmarkbundle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_feedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_feedtoken (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: bookmarks_globalsettings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_globalsettings (
    id integer NOT NULL,
    landing_page character varying(50) NOT NULL,
    guest_profile_user_id integer,
    enable_link_prefetch boolean NOT NULL
);


--
-- Name: bookmarks_globalsettings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_globalsettings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_globalsettings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_tag (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    date_added timestamp with time zone NOT NULL,
    owner_id integer NOT NULL
);


--
-- Name: bookmarks_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_toast; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_toast (
    id integer NOT NULL,
    key character varying(50) NOT NULL,
    message text NOT NULL,
    acknowledged boolean NOT NULL,
    owner_id integer NOT NULL
);


--
-- Name: bookmarks_toast_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_toast ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_toast_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks_userprofile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookmarks_userprofile (
    id integer NOT NULL,
    theme character varying(10) NOT NULL,
    user_id integer NOT NULL,
    bookmark_date_display character varying(10) NOT NULL,
    bookmark_link_target character varying(10) NOT NULL,
    web_archive_integration character varying(10) NOT NULL,
    enable_sharing boolean NOT NULL,
    enable_favicons boolean NOT NULL,
    tag_search character varying(10) NOT NULL,
    display_url boolean NOT NULL,
    permanent_notes boolean NOT NULL,
    enable_public_sharing boolean NOT NULL,
    search_preferences jsonb NOT NULL,
    custom_css text NOT NULL,
    bookmark_description_display character varying(10) NOT NULL,
    bookmark_description_max_lines integer NOT NULL,
    display_archive_bookmark_action boolean NOT NULL,
    display_edit_bookmark_action boolean NOT NULL,
    display_remove_bookmark_action boolean NOT NULL,
    display_view_bookmark_action boolean NOT NULL,
    enable_automatic_html_snapshots boolean NOT NULL,
    default_mark_unread boolean NOT NULL,
    enable_preview_images boolean NOT NULL,
    tag_grouping character varying(12) NOT NULL,
    auto_tagging_rules text NOT NULL,
    items_per_page integer NOT NULL,
    sticky_pagination boolean NOT NULL,
    custom_css_hash character varying(32) NOT NULL,
    collapse_side_panel boolean NOT NULL,
    hide_bundles boolean NOT NULL,
    default_mark_shared boolean NOT NULL,
    legacy_search boolean NOT NULL
);


--
-- Name: bookmarks_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookmarks_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: bookmarks_apitoken bookmarks_apitoken_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_apitoken
    ADD CONSTRAINT bookmarks_apitoken_key_key UNIQUE (key);


--
-- Name: bookmarks_apitoken bookmarks_apitoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_apitoken
    ADD CONSTRAINT bookmarks_apitoken_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_bookmark bookmarks_bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmark
    ADD CONSTRAINT bookmarks_bookmark_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_bookmark_tags bookmarks_bookmark_tags_bookmark_id_tag_id_1a999b75_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmark_tags
    ADD CONSTRAINT bookmarks_bookmark_tags_bookmark_id_tag_id_1a999b75_uniq UNIQUE (bookmark_id, tag_id);


--
-- Name: bookmarks_bookmark_tags bookmarks_bookmark_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmark_tags
    ADD CONSTRAINT bookmarks_bookmark_tags_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_bookmarkasset bookmarks_bookmarkasset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmarkasset
    ADD CONSTRAINT bookmarks_bookmarkasset_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_bookmarkbundle bookmarks_bookmarkbundle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmarkbundle
    ADD CONSTRAINT bookmarks_bookmarkbundle_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_feedtoken bookmarks_feedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_feedtoken
    ADD CONSTRAINT bookmarks_feedtoken_pkey PRIMARY KEY (key);


--
-- Name: bookmarks_feedtoken bookmarks_feedtoken_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_feedtoken
    ADD CONSTRAINT bookmarks_feedtoken_user_id_key UNIQUE (user_id);


--
-- Name: bookmarks_globalsettings bookmarks_globalsettings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_globalsettings
    ADD CONSTRAINT bookmarks_globalsettings_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_tag bookmarks_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_tag
    ADD CONSTRAINT bookmarks_tag_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_toast bookmarks_toast_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_toast
    ADD CONSTRAINT bookmarks_toast_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_userprofile bookmarks_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_userprofile
    ADD CONSTRAINT bookmarks_userprofile_pkey PRIMARY KEY (id);


--
-- Name: bookmarks_userprofile bookmarks_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_userprofile
    ADD CONSTRAINT bookmarks_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: bookmarks_apitoken_key_af12d964_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_apitoken_key_af12d964_like ON public.bookmarks_apitoken USING btree (key varchar_pattern_ops);


--
-- Name: bookmarks_apitoken_user_id_2181e9f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_apitoken_user_id_2181e9f8 ON public.bookmarks_apitoken USING btree (user_id);


--
-- Name: bookmarks_bookmark_latest_snapshot_id_ed3c8c2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmark_latest_snapshot_id_ed3c8c2b ON public.bookmarks_bookmark USING btree (latest_snapshot_id);


--
-- Name: bookmarks_bookmark_owner_id_051b24cc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmark_owner_id_051b24cc ON public.bookmarks_bookmark USING btree (owner_id);


--
-- Name: bookmarks_bookmark_tags_bookmark_id_fbe7b649; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmark_tags_bookmark_id_fbe7b649 ON public.bookmarks_bookmark_tags USING btree (bookmark_id);


--
-- Name: bookmarks_bookmark_tags_tag_id_6e32a767; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmark_tags_tag_id_6e32a767 ON public.bookmarks_bookmark_tags USING btree (tag_id);


--
-- Name: bookmarks_bookmark_url_normalized_8b3c53e4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmark_url_normalized_8b3c53e4 ON public.bookmarks_bookmark USING btree (url_normalized);


--
-- Name: bookmarks_bookmark_url_normalized_8b3c53e4_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmark_url_normalized_8b3c53e4_like ON public.bookmarks_bookmark USING btree (url_normalized varchar_pattern_ops);


--
-- Name: bookmarks_bookmarkasset_bookmark_id_42136c86; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmarkasset_bookmark_id_42136c86 ON public.bookmarks_bookmarkasset USING btree (bookmark_id);


--
-- Name: bookmarks_bookmarkbundle_owner_id_53ecd5a5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_bookmarkbundle_owner_id_53ecd5a5 ON public.bookmarks_bookmarkbundle USING btree (owner_id);


--
-- Name: bookmarks_feedtoken_key_8609bd53_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_feedtoken_key_8609bd53_like ON public.bookmarks_feedtoken USING btree (key varchar_pattern_ops);


--
-- Name: bookmarks_globalsettings_guest_profile_user_id_6d5cf00e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_globalsettings_guest_profile_user_id_6d5cf00e ON public.bookmarks_globalsettings USING btree (guest_profile_user_id);


--
-- Name: bookmarks_tag_owner_id_4c853e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_tag_owner_id_4c853e4b ON public.bookmarks_tag USING btree (owner_id);


--
-- Name: bookmarks_toast_owner_id_7fa00b79; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookmarks_toast_owner_id_7fa00b79 ON public.bookmarks_toast USING btree (owner_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_apitoken bookmarks_apitoken_user_id_2181e9f8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_apitoken
    ADD CONSTRAINT bookmarks_apitoken_user_id_2181e9f8_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_bookmark bookmarks_bookmark_latest_snapshot_id_ed3c8c2b_fk_bookmarks; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmark
    ADD CONSTRAINT bookmarks_bookmark_latest_snapshot_id_ed3c8c2b_fk_bookmarks FOREIGN KEY (latest_snapshot_id) REFERENCES public.bookmarks_bookmarkasset(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_bookmark bookmarks_bookmark_owner_id_051b24cc_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmark
    ADD CONSTRAINT bookmarks_bookmark_owner_id_051b24cc_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_bookmark_tags bookmarks_bookmark_t_bookmark_id_fbe7b649_fk_bookmarks; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmark_tags
    ADD CONSTRAINT bookmarks_bookmark_t_bookmark_id_fbe7b649_fk_bookmarks FOREIGN KEY (bookmark_id) REFERENCES public.bookmarks_bookmark(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_bookmark_tags bookmarks_bookmark_tags_tag_id_6e32a767_fk_bookmarks_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmark_tags
    ADD CONSTRAINT bookmarks_bookmark_tags_tag_id_6e32a767_fk_bookmarks_tag_id FOREIGN KEY (tag_id) REFERENCES public.bookmarks_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_bookmarkasset bookmarks_bookmarkas_bookmark_id_42136c86_fk_bookmarks; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmarkasset
    ADD CONSTRAINT bookmarks_bookmarkas_bookmark_id_42136c86_fk_bookmarks FOREIGN KEY (bookmark_id) REFERENCES public.bookmarks_bookmark(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_bookmarkbundle bookmarks_bookmarkbundle_owner_id_53ecd5a5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_bookmarkbundle
    ADD CONSTRAINT bookmarks_bookmarkbundle_owner_id_53ecd5a5_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_feedtoken bookmarks_feedtoken_user_id_47eef1a9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_feedtoken
    ADD CONSTRAINT bookmarks_feedtoken_user_id_47eef1a9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_globalsettings bookmarks_globalsett_guest_profile_user_i_6d5cf00e_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_globalsettings
    ADD CONSTRAINT bookmarks_globalsett_guest_profile_user_i_6d5cf00e_fk_auth_user FOREIGN KEY (guest_profile_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_tag bookmarks_tag_owner_id_4c853e4b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_tag
    ADD CONSTRAINT bookmarks_tag_owner_id_4c853e4b_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_toast bookmarks_toast_owner_id_7fa00b79_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_toast
    ADD CONSTRAINT bookmarks_toast_owner_id_7fa00b79_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmarks_userprofile bookmarks_userprofile_user_id_0dbae2c9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookmarks_userprofile
    ADD CONSTRAINT bookmarks_userprofile_user_id_0dbae2c9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;
