package auth

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"testing"

	"golang.org/x/crypto/argon2"
	"golang.org/x/crypto/bcrypt"
)

func TestVerifyPinnedDjangoPasswordHashes(t *testing.T) {
	// Generated by the pinned v1.47.0 Docker image with Django 6.0.7.
	vectors := []string{
		"pbkdf2_sha256$1200000$0ECrmJ59dYW6pHDpMJOaVI$qwaozCPlUlj7Qu9Jb2C9HWxOfTZRfZ7dUQRDzx1ovIw=",
		"pbkdf2_sha1$1200000$DMUQXD0QLlgl97a6oYmEtm$x3tJom9S0WkVjqpfm9qv5ldXo0E=",
		"scrypt$16384$JZK67TVW6OICtVSpxpmXik$8$5$TIcl66cvSztZoT0dU3H03GnnJDLLjVIXmW6j9CYFMKUlwTNQgBe20fg//O0H1TR4K2JQgVYm5QPjIrrB6oHobw==",
	}
	for _, encoded := range vectors {
		if ok, err := VerifyPassword("parity-password", encoded); err != nil || !ok {
			t.Fatalf("valid password for %q: ok=%v err=%v", encoded[:12], ok, err)
		}
		if ok, err := VerifyPassword("wrong", encoded); err != nil || ok {
			t.Fatalf("wrong password for %q: ok=%v err=%v", encoded[:12], ok, err)
		}
	}
}

func TestOptionalDjangoPasswordFormats(t *testing.T) {
	password := "parity-password"
	digest := sha256.Sum256([]byte(password))
	bcryptHash, err := bcrypt.GenerateFromPassword([]byte(hex.EncodeToString(digest[:])), bcrypt.MinCost)
	if err != nil {
		t.Fatal(err)
	}
	salt := []byte("DjangoArgonSalt123")
	argonHash := argon2.IDKey([]byte(password), salt, 2, 4096, 2, 32)
	vectors := []string{
		"bcrypt_sha256$" + string(bcryptHash),
		fmt.Sprintf("argon2$argon2id$v=19$m=4096,t=2,p=2$%s$%s", base64.RawStdEncoding.EncodeToString(salt), base64.RawStdEncoding.EncodeToString(argonHash)),
	}
	for _, encoded := range vectors {
		if ok, err := VerifyPassword(password, encoded); err != nil || !ok {
			t.Fatalf("valid password for %q: ok=%v err=%v", encoded[:7], ok, err)
		}
		if ok, err := VerifyPassword("wrong", encoded); err != nil || ok {
			t.Fatalf("wrong password for %q: ok=%v err=%v", encoded[:7], ok, err)
		}
	}
}

func TestPasswordHashValidation(t *testing.T) {
	if ok, err := VerifyPassword("anything", "!disabled"); err != nil || ok {
		t.Fatalf("unusable password: ok=%v err=%v", ok, err)
	}
	if _, err := VerifyPassword("x", "md5$..."); !errors.Is(err, ErrUnsupportedPasswordHash) {
		t.Fatalf("unknown hash: %v", err)
	}
	if _, err := VerifyPassword("x", "pbkdf2_sha256$999999999999$abc$bad"); !errors.Is(err, ErrInvalidPasswordHash) {
		t.Fatalf("invalid cost: %v", err)
	}
}

func TestHashPasswordUsesPinnedDefaultFormat(t *testing.T) {
	encoded, err := HashPassword("parity-password")
	if err != nil {
		t.Fatal(err)
	}
	if ok, err := VerifyPassword("parity-password", encoded); err != nil || !ok {
		t.Fatalf("generated hash: ok=%v err=%v", ok, err)
	}
}
